### ISSUE TITLE
ImportError: No module named 'bs4'

### ISSUE THREAD

**Issue by BeanBagKing** [lbarman/kali-tools#1]
I'm probably missing something obvious, but I've tried this on two systems so far (Workstation and Fusion), and received the same error both times. Am I missing a dependency? Using the wrong Python version?

**root@kali:~/kali-tools#** ./kali.py 
Traceback (most recent call last):
  File "./kali.py", line 9, in <module>
    from bs4 import BeautifulSoup, SoupStrainer
ImportError: No module named 'bs4'

**root@kali:~/kali-tools#** pip install bs4
Requirement already satisfied: bs4 in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages (from bs4)

**Comment by lbarman** [comment]
Hmm... Indeed. I think we're touching the "black magic" part of python here.

As you've correctly seen, "bs4" is for "Beautiful Soup", and I did install it exactly like you did. Two options in my opinion:

1. pip uninstall bs4, then install it system wide (something like sudo apt-get install python3-beautifulsoup)
2. remove the dependency. It is only used to leech the website, but not in the normal operations. So you can comment this line, and it should work exactly the same

**Comment by BeanBagKing** [comment]
Got it! 

There were no results for "python3-beautifulsoup", but several others if you search the cache. Not sure what distro you're on or why our packages seem to differ?
```
root@kali:~/kali-tools# apt-cache search beautifulsoup
pypy-bs4 - error-tolerant HTML parser for PyPy
python-beautifulsoup - error-tolerant HTML parser for Python
python-bs4 - error-tolerant HTML parser for Python
python-bs4-doc - error-tolerant HTML parser for Python - documentation
python3-bs4 - error-tolerant HTML parser for Python 3
python-pynliner - CSS-to-inline-styles conversion tool for HTML - Python 2.x
python3-pynliner - CSS-to-inline-styles conversion tool for HTML - Python 3.x
```

"python-beautifulsoup" was already installed and up to date, so my next guess was "**apt install python3-bs4**". This got everything working perfect, no need to pip uninstall or remove the dependency. Thanks for the system wide tip, that got me right to it.

**Comment by lbarman** [comment]
Sure thing. I'm also struggling with choosing between pip/apt for python packages, I try to got for system-wide whenever possible (hoping that this resolves dependencies), but the whole topic is still hacky to me.
Good that it works!
